// booksData.js (CommonJS version)
exports.books = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    year: 1960,
    status: "Available",
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: 1949,
    status: "Issued",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    year: 1925,
    status: "Available",
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    genre: "Adventure",
    year: 1851,
    status: "Available",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    year: 1813,
    status: "Issued",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    year: 1951,
    status: "Available",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    status: "Available",
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Dystopian",
    year: 1953,
    status: "Issued",
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Historical",
    year: 1869,
    status: "Available",
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Psychological",
    year: 1866,
    status: "Available",
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    genre: "Philosophical",
    year: 1880,
    status: "Issued",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: 1932,
    status: "Available",
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "Romance",
    year: 1847,
    status: "Issued",
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genre: "Classic",
    year: 1847,
    status: "Available",
  },
  {
    title: "The Odyssey",
    author: "Homer",
    genre: "Epic",
    year: -800,
    status: "Available",
  },
  {
    title: "The Iliad",
    author: "Homer",
    genre: "Epic",
    year: -750,
    status: "Available",
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    genre: "Classic",
    year: 1605,
    status: "Issued",
  },
  {
    title: "Les Misérables",
    author: "Victor Hugo",
    genre: "Historical",
    year: 1862,
    status: "Available",
  },
  {
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    genre: "Romance",
    year: 1877,
    status: "Issued",
  },
  {
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    genre: "Epic Poetry",
    year: 1320,
    status: "Available",
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Horror",
    year: 1897,
    status: "Available",
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Horror",
    year: 1818,
    status: "Issued",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1954,
    status: "Available",
  },
  {
    title: "Harry Potter and the Sorcerer’s Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1997,
    status: "Available",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1998,
    status: "Issued",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1999,
    status: "Available",
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 2000,
    status: "Available",
  },
  {
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 2003,
    status: "Issued",
  },
  {
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 2005,
    status: "Available",
  },
  {
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 2007,
    status: "Available",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    year: 1988,
    status: "Available",
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Drama",
    year: 2003,
    status: "Issued",
  },
  {
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    genre: "Drama",
    year: 2007,
    status: "Available",
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical",
    year: 2005,
    status: "Available",
  },
  {
    title: "Life of Pi",
    author: "Yann Martel",
    genre: "Adventure",
    year: 2001,
    status: "Available",
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: 2008,
    status: "Issued",
  },
  {
    title: "Catching Fire",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: 2009,
    status: "Available",
  },
  {
    title: "Mockingjay",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: 2010,
    status: "Available",
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    genre: "Romance",
    year: 2012,
    status: "Available",
  },
  {
    title: "Looking for Alaska",
    author: "John Green",
    genre: "Drama",
    year: 2005,
    status: "Issued",
  },
  {
    title: "Paper Towns",
    author: "John Green",
    genre: "Mystery",
    year: 2008,
    status: "Available",
  },
  {
    title: "The Shining",
    author: "Stephen King",
    genre: "Horror",
    year: 1977,
    status: "Available",
  },
  {
    title: "It",
    author: "Stephen King",
    genre: "Horror",
    year: 1986,
    status: "Issued",
  },
  {
    title: "Misery",
    author: "Stephen King",
    genre: "Thriller",
    year: 1987,
    status: "Available",
  },
  {
    title: "The Stand",
    author: "Stephen King",
    genre: "Post-Apocalyptic",
    year: 1978,
    status: "Available",
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Thriller",
    year: 2003,
    status: "Issued",
  },
  {
    title: "Angels & Demons",
    author: "Dan Brown",
    genre: "Thriller",
    year: 2000,
    status: "Available",
  },
  {
    title: "Inferno",
    author: "Dan Brown",
    genre: "Thriller",
    year: 2013,
    status: "Available",
  },
  {
    title: "Origin",
    author: "Dan Brown",
    genre: "Thriller",
    year: 2017,
    status: "Available",
  },
];
